name: "Register PoemAI Dependencies"
description: "Upload .poemai-dependencies.yaml to the central Lambda via S3"

inputs:
  role-to-assume:
    required: true
    description: "Full ARN of the role to assume via OIDC"
  region:
    required: true
    description: "AWS region"
  function-name:
    required: true
    description: "Lambda function to invoke for dependency registration"

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Prepare dependencies JSON payload
      shell: bash
      run: |
        DEP_YAML=$(cat .poemai-dependencies.yaml)
        PAYLOAD_JSON=$(jq -n \
          --arg repo "poemAI-ch/${{ github.event.repository.name }}" \
          --arg sha "${{ github.sha }}" \
          --arg deps_yaml "$DEP_YAML" \
          '{task_type: "store_dependencies", repo: $repo, sha: $sha, dependencies_yaml: $deps_yaml}')

        echo "PAYLOAD_JSON<<EOF" >> $GITHUB_ENV
        echo "$PAYLOAD_JSON" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

    - name: Register in S3 via Lambda
      uses: poemAI-ch/poemai-github-actions/invoke-lambda@v2
      with:
        function-name: ${{ inputs.function-name }}
        region: ${{ inputs.region }}
        role-to-assume: ${{ inputs.role-to-assume }}
        payload: ${{ env.PAYLOAD_JSON }}