name: 'Deploy poemai Config'
description: 'Deploy poemai configuration files via Lambda'
author: 'poemAI-ch'

inputs:
  environment:
    description: 'Environment to deploy to (production, staging, development)'
    required: true
  lambda-function-name:
    description: 'Name of the Lambda function to invoke for deployment'
    required: true
  role-to-assume:
    description: 'ARN of the AWS IAM role to assume'
    required: true
  aws-region:
    description: 'AWS region'
    required: false
    default: 'eu-central-2'
  project-root-path:
    description: 'Path to the project root containing environments/ directory'
    required: false
    default: '.'
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.12'
  version-id:
    description: 'Optional version identifier to associate with the configuration objects'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.role-to-assume }}
        aws-region: ${{ inputs.aws-region }}

    - name: Install dependencies
      shell: bash
      run: |
        pip install boto3 pyyaml

    - name: Deploy configuration via Lambda
      shell: bash
      run: |
        echo "🚀 Deploying poemai configuration..."
        echo "  Environment: ${{ inputs.environment }}"
        echo "  Lambda function: ${{ inputs.lambda-function-name }}"
        echo "  Project root: ${{ inputs.project-root-path }}"
        echo ""
        
        COMMIT_SHORT=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
        VERSION_ID="${{ inputs.version-id }}"
        if [ -z "$VERSION_ID" ]; then
          VERSION_ID="$COMMIT_SHORT"
        fi
        
        python ${{ github.action_path }}/deploy_config_with_lambda_call.py \
          --environment "${{ inputs.environment }}" \
          --lambda-function-name "${{ inputs.lambda-function-name }}" \
          --version-id "$VERSION_ID"
        
        echo "✅ Configuration deployment completed successfully!"

branding:
  icon: 'upload-cloud'
  color: 'blue'
