name: "Invoke AWS Lambda"
description: "Invoke an AWS Lambda using GitHub OIDC with explicit inputs. Make sure you have id_token permission in your workflow."

inputs:
  role-to-assume:
    description: "Full ARN of the IAM role to assume (required)"
    required: true
  function-name:
    description: "Name or ARN of the Lambda function"
    required: true
  region:
    description: "AWS region (default: eu-central-1)"
    required: false
    default: "eu-central-1"
  payload:
    description: "JSON payload as string or @file.json"
    required: false
    default: "{}"
  log-type:
    description: "Log type to request from Lambda (e.g., Tail)"
    required: false
    default: "None"

runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials via OIDC
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.role-to-assume }}
        aws-region: ${{ inputs.region }}

    - name: Invoke Lambda function
      shell: bash
      run: |
        echo "Invoking Lambda: ${{ inputs.function-name }}"
        aws lambda invoke \
          --function-name "${{ inputs.function-name }}" \
          --payload '${{ inputs.payload }}' \
          --log-type "${{ inputs.log-type }}" \
          --region "${{ inputs.region }}" \
          --cli-binary-format raw-in-base64-out \
          response.json